const fs = require('fs');
const path = require('path');

// Read existing zh-cn, ja, ko from asian.ts
const asianTs = fs.readFileSync('src/i18n/locales/asian.ts', 'utf8');

function extractDict(name) {
  const start = asianTs.indexOf('export const ' + name);
  const nextStart = asianTs.indexOf('export const ', start + 20);
  const chunk = nextStart !== -1 ? asianTs.slice(start, nextStart) : asianTs.slice(start);
  const dict = {};
  for (const m of chunk.matchAll(/'([a-zA-Z0-9\._]+)':\s*'((?:[^'\\]|\\.)*)'/g)) {
    dict[m[1]] = m[2];
  }
  return dict;
}

const zhCn = extractDict('zhCnTranslations');
const ja = extractDict('jaTranslations');
const ko = extractDict('koTranslations');

const zhTw = {
  'workspace.noFolderOpened': '未開啟資料夾',
  'workspace.openFolder': '開啟資料夾',
  'quickopen.placeholder': '依名稱搜尋檔案 (輸入 :行號 跳轉)...',
  'quickopen.noFilesFound': '找不到相符的檔案',

  'titlebar.hideSidebar': '隱藏側邊欄 (Ctrl+B)',
  'titlebar.showSidebar': '顯示側邊欄 (Ctrl+B)',
  'titlebar.newFile': '新增檔案 (Ctrl+N)',
  'titlebar.openFile': '開啟檔案 (Ctrl+O)',
  'titlebar.saveFile': '儲存檔案 (Ctrl+S)',
  'titlebar.wordWrap': '自動換行',
  'titlebar.minimap': '程式碼縮圖',
  'titlebar.commandPalette': '命令選擇區 (Ctrl+Shift+P)',
  'titlebar.settings': '開啟設定 (Ctrl+,)',
  'titlebar.run': '執行程式碼 (F5)',
  'titlebar.console': '輸出主控台',
  'titlebar.terminal': '終端機 (Ctrl+`)',
  'titlebar.minimize': '最小化',
  'titlebar.maximize': '最大化',
  'titlebar.restore': '向下還原',
  'titlebar.close': '關閉',

  'tabbar.newTab': '新增分頁 (Ctrl+N)',
  'tabbar.closeTab': '關閉分頁 (Ctrl+W)',
  'tabbar.unsaved': '未儲存的變更。點擊關閉。',
  'tabbar.settings': '設定',

  'tabmenu.close': '關閉',
  'tabmenu.closeOthers': '關閉其他分頁',
  'tabmenu.closeRight': '關閉右側分頁',
  'tabmenu.closeLeft': '關閉左側分頁',
  'tabmenu.closeSaved': '關閉已儲存分頁',
  'tabmenu.closeAll': '關閉所有分頁',
  'tabmenu.reopenClosed': '重新開啟已關閉的分頁',
  'tabmenu.rename': '重新命名...',
  'tabmenu.duplicate': '複製分頁',
  'tabmenu.copyPath': '複製完整路徑',
  'tabmenu.copyName': '複製檔案名稱',
  'tabmenu.revealInExplorer': '在檔案總管中顯示',
  'tabmenu.save': '儲存',

  'sidebar.openEditors': '已開啟的編輯器',
  'sidebar.newFile': '新增檔案',
  'sidebar.openFile': '開啟檔案',
  'sidebar.filesCount': '個開啟的檔案',
  'sidebar.settings': '設定 (Ctrl+,)',

  'statusbar.line': '行',
  'statusbar.col': '欄',
  'statusbar.selected': '已選取',
  'statusbar.spaces': '空格',
  'statusbar.encoding': '檔案編碼',
  'statusbar.eol': '行尾序列',
  'statusbar.selectLanguage': '選取語言模式',
  'statusbar.notifications': '通知',
  'statusbar.errors': '錯誤',
  'statusbar.warnings': '警告',
  'statusbar.searchLanguage': '選取語言模式 (例如 ts, python, cpp, json)...',
  'statusbar.noLanguages': '找不到相符的語言模式',

  'palette.placeholder': '輸入命令或進行搜尋...',
  'palette.escToClose': '按 ESC 關閉',
  'palette.noCommands': '找不到相符的命令',
  'palette.cat.file': '檔案',
  'palette.cat.edit': '編輯',
  'palette.cat.find': '尋找',
  'palette.cat.view': '檢視',
  'palette.cat.preferences': '偏好設定',
  'palette.cat.themes': '主題',
  'palette.cat.language': '語言',
  'palette.cmd.newFile': '新增檔案',
  'palette.cmd.openFile': '開啟檔案...',
  'palette.cmd.saveFile': '儲存目前檔案',
  'palette.cmd.saveAs': '另存新檔...',
  'palette.cmd.find': '在文件中尋找',
  'palette.cmd.replace': '尋找與取代',
  'palette.cmd.toggleComment': '切換行註解',
  'palette.cmd.selectNext': '選取下一個相符項',
  'palette.cmd.gotoLine': '跳轉至行...',
  'palette.cmd.selectAll': '全選',
  'palette.cmd.undo': '復原',
  'palette.cmd.redo': '重做',
  'palette.cmd.nextTab': '下一個分頁',
  'palette.cmd.prevTab': '上一個分頁',
  'palette.cmd.closeTab': '關閉目前分頁',
  'palette.cmd.toggleSidebar': '切換側邊欄',
  'palette.cmd.toggleWordWrap': '切換自動換行',
  'palette.cmd.toggleMinimap': '切換程式碼縮圖',
  'palette.cmd.openSettings': '開啟設定介面',
  'palette.cmd.colorTheme': '色彩佈景主題',
  'palette.cmd.changeLanguage': '變更語言模式',
  'palette.cmd.changeDisplayLanguage': '變更介面顯示語言',

  'settings.title': '設定',
  'settings.preferences': '/ 偏好設定',
  'settings.backToEditor': '返回編輯器',
  'settings.resetAll': '全部重設',
  'settings.searchPlaceholder': '搜尋設定 (佈景主題, 字型, 語言, 縮排)...',
  'settings.categories': '設定分類',
  'settings.cat.commonlyUsed': '常用設定',
  'settings.cat.appearance': '外觀與主題',
  'settings.cat.editor': '文字編輯器',
  'settings.cat.files': '檔案與工作階段',
  'settings.cat.language': '介面顯示語言',

  'settings.preview.title': '編輯器即時預覽',
  'settings.preview.realtime': '(即時更新)',
  'settings.preview.theme': '主題',
  'settings.preview.font': '字型',
  'settings.preview.tab': '縮排',

  'settings.displayLanguage.title': '應用程式: 顯示語言',
  'settings.displayLanguage.desc': '設定 HyperEdit 編輯器的使用者介面語言。',
  'settings.theme.title': '工作區: 色彩佈景主題',
  'settings.theme.desc': '指定在應用程式視窗與程式碼編輯器中使用的色彩主題。',
  'settings.fontFamily.title': '編輯器: 字型系列',
  'settings.fontFamily.desc': '控制用於呈現程式碼行的字型系列。',
  'settings.fontSize.title': '編輯器: 字型大小',
  'settings.fontSize.desc': '控制編輯器字型大小 (像素)。',
  'settings.lineHeight.title': '編輯器: 行高',
  'settings.lineHeight.desc': '編輯器內容的行高倍數。',
  'settings.tabSize.title': '編輯器: Tab 鍵大小',
  'settings.tabSize.desc': '一個 Tab 等同的空格數量。',
  'settings.tabSize.spaces': '空格',
  'settings.wordWrap.title': '編輯器: 自動換行',
  'settings.wordWrap.desc': '控制編輯器長行如何折行。',
  'settings.minimap.title': '編輯器 > 縮圖: 已啟用',
  'settings.minimap.desc': '控制是否在右側顯示互動式程式碼縮圖。',
  'settings.cursorBlinking.title': '編輯器: 游標閃爍動畫',
  'settings.cursorBlinking.desc': '控制文字游標的閃爍樣式。',
  'settings.cursorBlinking.smooth': '平滑呼吸 (VS Code 風格)',
  'settings.cursorBlinking.blink': '傳統閃爍',
  'settings.cursorBlinking.solid': '持續常亮',
  'settings.lineNumbers.title': '編輯器: 行號',
  'settings.lineNumbers.desc': '控制行號邊界之行號的顯示。',
  'settings.lineNumbers.on': '開啟',
  'settings.lineNumbers.off': '關閉',
  'settings.bracketMatching.title': '編輯器: 括號對應',
  'settings.bracketMatching.desc': '游標靠近時突顯對應的括號。',
  'settings.autoCloseBrackets.title': '編輯器: 自動閉合括號',
  'settings.autoCloseBrackets.desc': '控制編輯器是否自動插入成對括號與引號。',
  'settings.activeLine.title': '編輯器: 呈現目前行突顯',
  'settings.activeLine.desc': '控制編輯器如何突顯游標所在的目前行。',
  'settings.codeFolding.title': '編輯器: 程式碼摺疊',
  'settings.codeFolding.desc': '控制編輯器邊界是否啟用程式碼摺疊。',
  'settings.colorDecorators.title': '編輯器: 色彩裝飾器',
  'settings.colorDecorators.desc': '控制編輯器是否顯示內嵌顏色方塊與色盤選擇器。',
  'settings.renderWhitespace.title': '編輯器: 轉譯空白字元',
  'settings.renderWhitespace.desc': '控制編輯器如何轉譯空白字元與 Tab。',
  'settings.renderWhitespace.none': '無 (隱藏)',
  'settings.renderWhitespace.all': '全部 (顯示點與符號)',
  'settings.sessionRestore.title': '檔案: 工作階段還原 (Notepad++ 風格)',
  'settings.sessionRestore.desc': '重啟時自動還原已開啟的分頁與未儲存的草稿。',
  'settings.trimWhitespace.title': '檔案: 修剪行尾空格',
  'settings.trimWhitespace.desc': '反白並在編輯儲存時刪除行尾多餘空白。',
  'settings.eol.title': '檔案: 預設行結尾字元',
  'settings.eol.desc': '預設行尾換行字元 (Unix/macOS 為 LF, Windows 為 CRLF)。',
  'settings.hotkeysHint': '快速鍵:',
  'settings.autoSaved': '已儲存至磁碟',
  'settings.saveNotice': '所有設定均會自動儲存至磁碟，重啟後依然保留。',

  'empty.noDocumentOpen': '未開啟任何文件或專案。請選擇下方動作以開始：',
  'empty.project': '專案:',
  'empty.newFile': '新增檔案',
  'empty.openFile': '開啟檔案...',
  'empty.openFolder': '開啟資料夾 / 專案...',
  'empty.quickOpen': '快速切換檔案',
  'empty.commandPalette': '命令選擇區',
  'empty.openSettings': 'HyperEdit 設定',

  'bottompanel.console': '輸出主控台',
  'bottompanel.terminal': '終端機',
  'bottompanel.split': '分割檢視',
  'bottompanel.run': '執行 (F5)',
  'bottompanel.clear': '清除',
  'bottompanel.stop': '停止',
  'bottompanel.copyAll': '複製全部',
};

const vi = {
  'workspace.noFolderOpened': 'Chưa mở thư mục nào',
  'workspace.openFolder': 'Mở thư mục',
  'quickopen.placeholder': 'Tìm tệp theo tên (gõ :dòng để điều hướng)...',
  'quickopen.noFilesFound': 'Không tìm thấy tệp phù hợp',

  'titlebar.hideSidebar': 'Ẩn thanh bên (Ctrl+B)',
  'titlebar.showSidebar': 'Hiện thanh bên (Ctrl+B)',
  'titlebar.newFile': 'Tệp mới (Ctrl+N)',
  'titlebar.openFile': 'Mở tệp (Ctrl+O)',
  'titlebar.saveFile': 'Lưu tệp (Ctrl+S)',
  'titlebar.wordWrap': 'Tự động xuống dòng',
  'titlebar.minimap': 'Bản đồ thu nhỏ',
  'titlebar.commandPalette': 'Bảng lệnh (Ctrl+Shift+P)',
  'titlebar.settings': 'Mở cài đặt (Ctrl+,)',
  'titlebar.run': 'Chạy mã (F5)',
  'titlebar.console': 'Bảng điều khiển xuất',
  'titlebar.terminal': 'Terminal (Ctrl+`)',
  'titlebar.minimize': 'Thu nhỏ',
  'titlebar.maximize': 'Phóng to',
  'titlebar.restore': 'Khôi phục',
  'titlebar.close': 'Đóng',

  'tabbar.newTab': 'Tab mới (Ctrl+N)',
  'tabbar.closeTab': 'Đóng tab (Ctrl+W)',
  'tabbar.unsaved': 'Thay đổi chưa lưu. Nhấp để đóng.',
  'tabbar.settings': 'Cài đặt',

  'tabmenu.close': 'Đóng',
  'tabmenu.closeOthers': 'Đóng các tab khác',
  'tabmenu.closeRight': 'Đóng các tab bên phải',
  'tabmenu.closeLeft': 'Đóng các tab bên trái',
  'tabmenu.closeSaved': 'Đóng các tab đã lưu',
  'tabmenu.closeAll': 'Đóng tất cả tab',
  'tabmenu.reopenClosed': 'Mở lại tab vừa đóng',
  'tabmenu.rename': 'Đổi tên...',
  'tabmenu.duplicate': 'Nhân bản tab',
  'tabmenu.copyPath': 'Sao chép đường dẫn',
  'tabmenu.copyName': 'Sao chép tên tệp',
  'tabmenu.revealInExplorer': 'Hiển thị trong File Explorer',
  'tabmenu.save': 'Lưu',

  'sidebar.openEditors': 'Trình chỉnh sửa đang mở',
  'sidebar.newFile': 'Tệp mới',
  'sidebar.openFile': 'Mở tệp',
  'sidebar.filesCount': 'tệp đang mở',
  'sidebar.settings': 'Cài đặt (Ctrl+,)',

  'statusbar.line': 'Dòng',
  'statusbar.col': 'Cột',
  'statusbar.selected': 'đã chọn',
  'statusbar.spaces': 'Dấu cách',
  'statusbar.encoding': 'Mã hóa tệp',
  'statusbar.eol': 'Ký tự kết dòng',
  'statusbar.selectLanguage': 'Chọn chế độ ngôn ngữ',
  'statusbar.notifications': 'Thông báo',
  'statusbar.errors': 'Lỗi',
  'statusbar.warnings': 'Cảnh báo',
  'statusbar.searchLanguage': 'Chọn chế độ ngôn ngữ (vd: ts, python, cpp, json)...',
  'statusbar.noLanguages': 'Không tìm thấy ngôn ngữ phù hợp',

  'palette.placeholder': 'Nhập lệnh hoặc tìm kiếm...',
  'palette.escToClose': 'để đóng',
  'palette.noCommands': 'Không tìm thấy lệnh phù hợp',
  'palette.cat.file': 'Tệp',
  'palette.cat.edit': 'Chỉnh sửa',
  'palette.cat.find': 'Tìm kiếm',
  'palette.cat.view': 'Xem',
  'palette.cat.preferences': 'Tùy chọn',
  'palette.cat.themes': 'Chủ đề',
  'palette.cat.language': 'Ngôn ngữ',
  'palette.cmd.newFile': 'Tệp mới',
  'palette.cmd.openFile': 'Mở tệp...',
  'palette.cmd.saveFile': 'Lưu tệp hiện tại',
  'palette.cmd.saveAs': 'Lưu dưới dạng...',
  'palette.cmd.find': 'Tìm trong tài liệu',
  'palette.cmd.replace': 'Tìm và thay thế',
  'palette.cmd.toggleComment': 'Bật/tắt chú thích dòng',
  'palette.cmd.selectNext': 'Chọn kết quả tiếp theo',
  'palette.cmd.gotoLine': 'Đi đến dòng...',
  'palette.cmd.selectAll': 'Chọn tất cả',
  'palette.cmd.undo': 'Hoàn tác',
  'palette.cmd.redo': 'Làm lại',
  'palette.cmd.nextTab': 'Tab tiếp theo',
  'palette.cmd.prevTab': 'Tab trước đó',
  'palette.cmd.closeTab': 'Đóng tab hiện tại',
  'palette.cmd.toggleSidebar': 'Bật/tắt thanh bên',
  'palette.cmd.toggleWordWrap': 'Bật/tắt xuống dòng tự động',
  'palette.cmd.toggleMinimap': 'Bật/tắt bản đồ thu nhỏ',
  'palette.cmd.openSettings': 'Mở cài đặt (Giao diện)',
  'palette.cmd.colorTheme': 'Chủ đề màu sắc',
  'palette.cmd.changeLanguage': 'Đổi chế độ ngôn ngữ',
  'palette.cmd.changeDisplayLanguage': 'Đổi ngôn ngữ hiển thị',

  'settings.title': 'Cài đặt',
  'settings.preferences': '/ Tùy chọn',
  'settings.backToEditor': 'Quay lại trình chỉnh sửa',
  'settings.resetAll': 'Đặt lại tất cả',
  'settings.searchPlaceholder': 'Tìm cài đặt (chủ đề, phông chữ, ngôn ngữ, tab)...',
  'settings.categories': 'Danh mục',
  'settings.cat.commonlyUsed': 'Thường dùng',
  'settings.cat.appearance': 'Giao diện & Chủ đề',
  'settings.cat.editor': 'Trình soạn thảo văn bản',
  'settings.cat.files': 'Tệp & Phiên làm việc',
  'settings.cat.language': 'Ngôn ngữ hiển thị',

  'settings.preview.title': 'Xem trước trực tiếp',
  'settings.preview.realtime': '(Cập nhật thời gian thực)',
  'settings.preview.theme': 'Chủ đề',
  'settings.preview.font': 'Phông chữ',
  'settings.preview.tab': 'Tab',

  'settings.displayLanguage.title': 'Ứng dụng: Ngôn ngữ hiển thị',
  'settings.displayLanguage.desc': 'Cấu hình ngôn ngữ giao diện của HyperEdit.',
  'settings.theme.title': 'Không gian làm việc: Chủ đề màu',
  'settings.theme.desc': 'Chỉ định chủ đề màu được sử dụng trong cửa sổ và trình chỉnh sửa.',
  'settings.fontFamily.title': 'Trình chỉnh sửa: Phông chữ',
  'settings.fontFamily.desc': 'Điều khiển phông chữ hiển thị văn bản mã nguồn.',
  'settings.fontSize.title': 'Trình chỉnh sửa: Cỡ chữ',
  'settings.fontSize.desc': 'Điều khiển kích thước phông chữ theo pixel.',
  'settings.lineHeight.title': 'Trình chỉnh sửa: Chiều cao dòng',
  'settings.lineHeight.desc': 'Hệ số khoảng cách giữa các dòng trong trình soạn thảo.',
  'settings.tabSize.title': 'Trình chỉnh sửa: Kích thước tab',
  'settings.tabSize.desc': 'Số khoảng trắng tương đương với một phím Tab.',
  'settings.tabSize.spaces': 'Dấu cách',
  'settings.wordWrap.title': 'Trình chỉnh sửa: Xuống dòng tự động',
  'settings.wordWrap.desc': 'Điều khiển cách các dòng dài tự động xuống dòng.',
  'settings.minimap.title': 'Trình chỉnh sửa > Bản đồ thu nhỏ: Bật',
  'settings.minimap.desc': 'Điều khiển việc hiển thị sơ đồ mã nguồn thu nhỏ bên phải.',
  'settings.cursorBlinking.title': 'Trình chỉnh sửa: Hoạt ảnh nhấp nháy con trỏ',
  'settings.cursorBlinking.desc': 'Điều khiển kiểu nhấp nháy hoặc thở của con trỏ.',
  'settings.cursorBlinking.smooth': 'Thở mượt mà (Kiểu VS Code)',
  'settings.cursorBlinking.blink': 'Nhấp nháy cổ điển',
  'settings.cursorBlinking.solid': 'Cố định không nhấp nháy',
  'settings.lineNumbers.title': 'Trình chỉnh sửa: Số dòng',
  'settings.lineNumbers.desc': 'Điều khiển hiển thị số dòng ở lề trái.',
  'settings.lineNumbers.on': 'Bật',
  'settings.lineNumbers.off': 'Tắt',
  'settings.bracketMatching.title': 'Trình chỉnh sửa: Khớp dấu ngoặc',
  'settings.bracketMatching.desc': 'Làm nổi bật dấu ngoặc tương ứng khi con trỏ ở gần.',
  'settings.autoCloseBrackets.title': 'Trình chỉnh sửa: Tự động đóng ngoặc',
  'settings.autoCloseBrackets.desc': 'Tự động chèn dấu ngoặc và dấu nháy đóng tương ứng.',
  'settings.activeLine.title': 'Trình chỉnh sửa: Làm nổi bật dòng hiện tại',
  'settings.activeLine.desc': 'Điều khiển cách làm nổi bật dòng đang chứa con trỏ.',
  'settings.codeFolding.title': 'Trình chỉnh sửa: Thu gọn khối mã',
  'settings.codeFolding.desc': 'Cho phép thu gọn các hàm và khối lệnh trong rãnh lề.',
  'settings.colorDecorators.title': 'Trình chỉnh sửa: Bộ chọn màu nội dòng',
  'settings.colorDecorators.desc': 'Hiển thị ô mẫu màu và bảng chọn màu cho mã hex/rgb/hsl.',
  'settings.renderWhitespace.title': 'Trình chỉnh sửa: Ký tự khoảng trắng',
  'settings.renderWhitespace.desc': 'Hiển thị các ký tự khoảng trắng và tab vô hình.',
  'settings.renderWhitespace.none': 'Không (Ẩn)',
  'settings.renderWhitespace.all': 'Tất cả (Hiện dấu chấm)',
  'settings.sessionRestore.title': 'Tệp: Khôi phục phiên làm việc (Kiểu Notepad++)',
  'settings.sessionRestore.desc': 'Tự động khôi phục các tab đã mở và bản nháp khi khởi động lại.',
  'settings.trimWhitespace.title': 'Tệp: Cắt khoảng trắng cuối dòng',
  'settings.trimWhitespace.desc': 'Làm nổi bật và loại bỏ khoảng trắng thừa ở cuối dòng khi lưu.',
  'settings.eol.title': 'Tệp: Ký tự kết thúc dòng mặc định',
  'settings.eol.desc': 'Ký tự xuống dòng mặc định (LF cho Unix/macOS, CRLF cho Windows).',
  'settings.hotkeysHint': 'Phím tắt:',
  'settings.autoSaved': 'Đã lưu vào đĩa',
  'settings.saveNotice': 'Mọi cài đặt được lưu tự động và duy trì sau khi khởi động lại.',

  'empty.noDocumentOpen': 'Chưa mở tài liệu hoặc dự án nào. Chọn một thao tác dưới đây để bắt đầu:',
  'empty.project': 'Dự án:',
  'empty.newFile': 'Tệp mới',
  'empty.openFile': 'Mở tệp...',
  'empty.openFolder': 'Mở thư mục / Dự án...',
  'empty.quickOpen': 'Tìm tệp nhanh',
  'empty.commandPalette': 'Bảng lệnh',
  'empty.openSettings': 'Cài đặt HyperEdit',

  'bottompanel.console': 'Bảng điều khiển xuất',
  'bottompanel.terminal': 'Terminal',
  'bottompanel.split': 'Chia đôi',
  'bottompanel.run': 'Chạy (F5)',
  'bottompanel.clear': 'Xóa sạch',
  'bottompanel.stop': 'Dừng lại',
  'bottompanel.copyAll': 'Sao chép tất cả',
};

const th = {
  'workspace.noFolderOpened': 'ไม่ได้เปิดโฟลเดอร์',
  'workspace.openFolder': 'เปิดโฟลเดอร์',
  'quickopen.placeholder': 'ค้นหาไฟล์ตามชื่อ (พิมพ์ :บรรทัด เพื่อนำทาง)...',
  'quickopen.noFilesFound': 'ไม่พบไฟล์ที่ตรงกัน',

  'titlebar.hideSidebar': 'ซ่อนแถบด้านข้าง (Ctrl+B)',
  'titlebar.showSidebar': 'แสดงแถบด้านข้าง (Ctrl+B)',
  'titlebar.newFile': 'สร้างไฟล์ใหม่ (Ctrl+N)',
  'titlebar.openFile': 'เปิดไฟล์ (Ctrl+O)',
  'titlebar.saveFile': 'บันทึกไฟล์ (Ctrl+S)',
  'titlebar.wordWrap': 'ตัดคำอัตโนมัติ',
  'titlebar.minimap': 'แผนผังโค้ดย่อส่วน',
  'titlebar.commandPalette': 'แผงคำสั่ง (Ctrl+Shift+P)',
  'titlebar.settings': 'เปิดการตั้งค่า (Ctrl+,)',
  'titlebar.run': 'เรียกใช้โค้ด (F5)',
  'titlebar.console': 'คอนโซลเอาต์พุต',
  'titlebar.terminal': 'เทอร์มินัล (Ctrl+`)',
  'titlebar.minimize': 'ย่อขนาด',
  'titlebar.maximize': 'ขยายขนาด',
  'titlebar.restore': 'คืนค่า',
  'titlebar.close': 'ปิด',

  'tabbar.newTab': 'แท็บใหม่ (Ctrl+N)',
  'tabbar.closeTab': 'ปิดแท็บ (Ctrl+W)',
  'tabbar.unsaved': 'ยังไม่ได้บันทึกการเปลี่ยนแปลง คลิกเพื่อปิด',
  'tabbar.settings': 'การตั้งค่า',

  'tabmenu.close': 'ปิด',
  'tabmenu.closeOthers': 'ปิดแท็บอื่น',
  'tabmenu.closeRight': 'ปิดแท็บทางขวา',
  'tabmenu.closeLeft': 'ปิดแท็บทางซ้าย',
  'tabmenu.closeSaved': 'ปิดแท็บที่บันทึกแล้ว',
  'tabmenu.closeAll': 'ปิดแท็บทั้งหมด',
  'tabmenu.reopenClosed': 'เปิดแท็บที่เพิ่งปิดใหม่',
  'tabmenu.rename': 'เปลี่ยนชื่อ...',
  'tabmenu.duplicate': 'ทำซ้ำแท็บ',
  'tabmenu.copyPath': 'คัดลอกเส้นทางเต็ม',
  'tabmenu.copyName': 'คัดลอกชื่อไฟล์',
  'tabmenu.revealInExplorer': 'แสดงใน File Explorer',
  'tabmenu.save': 'บันทึก',

  'sidebar.openEditors': 'ตัวแก้ไขที่เปิดอยู่',
  'sidebar.newFile': 'ไฟล์ใหม่',
  'sidebar.openFile': 'เปิดไฟล์',
  'sidebar.filesCount': 'ไฟล์ที่เปิดอยู่',
  'sidebar.settings': 'การตั้งค่า (Ctrl+,)',

  'statusbar.line': 'บรรทัด',
  'statusbar.col': 'คอลัมน์',
  'statusbar.selected': 'เลือกแล้ว',
  'statusbar.spaces': 'ช่องว่าง',
  'statusbar.encoding': 'การเข้ารหัสไฟล์',
  'statusbar.eol': 'การสิ้นสุดบรรทัด',
  'statusbar.selectLanguage': 'เลือกโหมดภาษา',
  'statusbar.notifications': 'การแจ้งเตือน',
  'statusbar.errors': 'ข้อผิดพลาด',
  'statusbar.warnings': 'คำเตือน',
  'statusbar.searchLanguage': 'เลือกโหมดภาษา (เช่น ts, python, cpp, json)...',
  'statusbar.noLanguages': 'ไม่พบโหมดภาษาที่ตรงกัน',

  'palette.placeholder': 'พิมพ์คำสั่งหรือค้นหา...',
  'palette.escToClose': 'เพื่อปิด',
  'palette.noCommands': 'ไม่พบคำสั่งที่ตรงกัน',
  'palette.cat.file': 'ไฟล์',
  'palette.cat.edit': 'แก้ไข',
  'palette.cat.find': 'ค้นหา',
  'palette.cat.view': 'มุมมอง',
  'palette.cat.preferences': 'การตั้งค่า',
  'palette.cat.themes': 'ธีม',
  'palette.cat.language': 'ภาษา',
  'palette.cmd.newFile': 'สร้างไฟล์ใหม่',
  'palette.cmd.openFile': 'เปิดไฟล์...',
  'palette.cmd.saveFile': 'บันทึกไฟล์ปัจจุบัน',
  'palette.cmd.saveAs': 'บันทึกเป็น...',
  'palette.cmd.find': 'ค้นหาในเอกสาร',
  'palette.cmd.replace': 'ค้นหาและแทนที่',
  'palette.cmd.toggleComment': 'สลับความคิดเห็นบรรทัด',
  'palette.cmd.selectNext': 'เลือกรายการที่ตรงกันถัดไป',
  'palette.cmd.gotoLine': 'ไปยังบรรทัด...',
  'palette.cmd.selectAll': 'เลือกทั้งหมด',
  'palette.cmd.undo': 'เลิกทำ',
  'palette.cmd.redo': 'ทำซ้ำ',
  'palette.cmd.nextTab': 'แท็บถัดไป',
  'palette.cmd.prevTab': 'แท็บก่อนหน้า',
  'palette.cmd.closeTab': 'ปิดแท็บปัจจุบัน',
  'palette.cmd.toggleSidebar': 'สลับแถบด้านข้าง',
  'palette.cmd.toggleWordWrap': 'สลับการตัดคำอัตโนมัติ',
  'palette.cmd.toggleMinimap': 'สลับแผนผังย่อส่วน',
  'palette.cmd.openSettings': 'เปิดการตั้งค่า (UI)',
  'palette.cmd.colorTheme': 'ธีมสี',
  'palette.cmd.changeLanguage': 'เปลี่ยนโหมดภาษา',
  'palette.cmd.changeDisplayLanguage': 'เปลี่ยนภาษาอินเทอร์เฟซ',

  'settings.title': 'การตั้งค่า',
  'settings.preferences': '/ การตั้งค่ากำหนด',
  'settings.backToEditor': 'กลับสู่ตัวแก้ไข',
  'settings.resetAll': 'รีเซ็ตทั้งหมด',
  'settings.searchPlaceholder': 'ค้นหาการตั้งค่า (ธีม, ฟอนต์, ภาษา, แท็บ)...',
  'settings.categories': 'หมวดหมู่',
  'settings.cat.commonlyUsed': 'ที่ใช้บ่อย',
  'settings.cat.appearance': 'ลักษณะที่ปรากฏและธีม',
  'settings.cat.editor': 'ตัวแก้ไขข้อความ',
  'settings.cat.files': 'ไฟล์และเซสชัน',
  'settings.cat.language': 'ภาษาอินเทอร์เฟซ',

  'settings.preview.title': 'แสดงตัวอย่างตัวแก้ไขแบบเรียลไทม์',
  'settings.preview.realtime': '(อัปเดตแบบเรียลไทม์)',
  'settings.preview.theme': 'ธีม',
  'settings.preview.font': 'ฟอนต์',
  'settings.preview.tab': 'แท็บ',

  'settings.displayLanguage.title': 'แอปพลิเคชัน: ภาษาที่แสดง',
  'settings.displayLanguage.desc': 'กำหนดค่าภาษาอินเทอร์เฟซผู้ใช้ของ HyperEdit',
  'settings.theme.title': 'พื้นที่ทำงาน: ธีมสี',
  'settings.theme.desc': 'ระบุธีมสีที่ใช้ในหน้าต่างแอปพลิเคชันและตัวแก้ไขโค้ด',
  'settings.fontFamily.title': 'ตัวแก้ไข: ตระกูลแบบอักษร',
  'settings.fontFamily.desc': 'ควบคุมแบบอักษรที่ใช้แสดงผลบรรทัดในตัวแก้ไข',
  'settings.fontSize.title': 'ตัวแก้ไข: ขนาดแบบอักษร',
  'settings.fontSize.desc': 'ควบคุมขนาดแบบอักษรเป็นพิกเซล',
  'settings.lineHeight.title': 'ตัวแก้ไข: ความสูงบรรทัด',
  'settings.lineHeight.desc': 'ตัวคูณระยะห่างระหว่างบรรทัดเนื้อหาตัวแก้ไข',
  'settings.tabSize.title': 'ตัวแก้ไข: ขนาดแท็บ',
  'settings.tabSize.desc': 'จำนวนช่องว่างที่เทียบเท่ากับหนึ่งแท็บ',
  'settings.tabSize.spaces': 'ช่องว่าง',
  'settings.wordWrap.title': 'ตัวแก้ไข: ตัดคำอัตโนมัติ',
  'settings.wordWrap.desc': 'ควบคุมวิธีการตัดบรรทัดยาวในตัวแก้ไข',
  'settings.minimap.title': 'ตัวแก้ไข > แผนผังย่อ: เปิดใช้งาน',
  'settings.minimap.desc': 'ควบคุมการแสดงแถบโครงร่างโค้ดย่อส่วนแนวตั้งทางขวา',
  'settings.cursorBlinking.title': 'ตัวแก้ไข: ภาพเคลื่อนไหวกะพริบของเคอร์เซอร์',
  'settings.cursorBlinking.desc': 'ควบคุมลักษณะการเคลื่อนไหวของการกะพริบของเคอร์เซอร์',
  'settings.cursorBlinking.smooth': 'หายใจแบบนุ่มนวล (สไตล์ VS Code)',
  'settings.cursorBlinking.blink': 'กะพริบแบบคลาสสิก',
  'settings.cursorBlinking.solid': 'คงที่ไม่กะพริบ',
  'settings.lineNumbers.title': 'ตัวแก้ไข: หมายเลขบรรทัด',
  'settings.lineNumbers.desc': 'ควบคุมการแสดงหมายเลขบรรทัดในรางด้านข้าง',
  'settings.lineNumbers.on': 'เปิด',
  'settings.lineNumbers.off': 'ปิด',
  'settings.bracketMatching.title': 'ตัวแก้ไข: จับคู่วงเล็บ',
  'settings.bracketMatching.desc': 'ไฮไลต์วงเล็บที่ตรงกันเมื่อเคอร์เซอร์อยู่ใกล้',
  'settings.autoCloseBrackets.title': 'ตัวแก้ไข: ปิดวงเล็บอัตโนมัติ',
  'settings.autoCloseBrackets.desc': 'ใส่คู่วงเล็บและเครื่องหมายคำพูดปิดโดยอัตโนมัติ',
  'settings.activeLine.title': 'ตัวแก้ไข: ไฮไลต์บรรทัดปัจจุบัน',
  'settings.activeLine.desc': 'ควบคุมวิธีการไฮไลต์บรรทัดที่เคอร์เซอร์กำลังทำงานอยู่',
  'settings.codeFolding.title': 'ตัวแก้ไข: การพับโค้ด',
  'settings.codeFolding.desc': 'เปิดใช้งานการพับบล็อกโค้ดในรางด้านข้าง',
  'settings.colorDecorators.title': 'ตัวแก้ไข: แสดงตัวอย่างสี',
  'settings.colorDecorators.desc': 'แสดงตัวอย่างสีในบรรทัดและตัวเลือกสีสำหรับ hex/rgb/hsl',
  'settings.renderWhitespace.title': 'ตัวแก้ไข: แสดงอักขระช่องว่าง',
  'settings.renderWhitespace.desc': 'ควบคุมการแสดงผลอักขระช่องว่างและแท็บที่ซ่อนอยู่',
  'settings.renderWhitespace.none': 'ไม่มี (ซ่อน)',
  'settings.renderWhitespace.all': 'ทั้งหมด (แสดงจุดและสัญลักษณ์)',
  'settings.sessionRestore.title': 'ไฟล์: การคืนค่าเซสชัน (สไตล์ Notepad++)',
  'settings.sessionRestore.desc': 'กู้คืนแท็บที่เปิดและฉบับร่างที่ยังไม่ได้บันทึกอัตโนมัติเมื่อเปิดใหม่',
  'settings.trimWhitespace.title': 'ไฟล์: ตัดช่องว่างต่อท้าย',
  'settings.trimWhitespace.desc': 'ลบช่องว่างส่วนเกินที่ส่วนท้ายของบรรทัดเมื่อบันทึก',
  'settings.eol.title': 'ไฟล์: อักขระสิ้นสุดบรรทัดเริ่มต้น',
  'settings.eol.desc': 'อักขระขึ้นบรรทัดใหม่เริ่มต้น (LF สำหรับ Unix/macOS, CRLF สำหรับ Windows)',
  'settings.hotkeysHint': 'ปุ่มลัด:',
  'settings.autoSaved': 'บันทึกลงในดิสก์แล้ว',
  'settings.saveNotice': 'การตั้งค่าทั้งหมดจะถูกบันทึกอัตโนมัติและคงอยู่แม้เริ่มใหม่',

  'empty.noDocumentOpen': 'ไม่ได้เปิดเอกสารหรือโปรเจกต์ใดๆ เลือกการดำเนินการด้านล่างเพื่อเริ่มต้น:',
  'empty.project': 'โปรเจกต์:',
  'empty.newFile': 'สร้างไฟล์ใหม่',
  'empty.openFile': 'เปิดไฟล์...',
  'empty.openFolder': 'เปิดโฟลเดอร์ / โปรเจกต์...',
  'empty.quickOpen': 'เปิดไฟล์ด่วน',
  'empty.commandPalette': 'แผงคำสั่ง',
  'empty.openSettings': 'การตั้งค่า HyperEdit',

  'bottompanel.console': 'คอนโซลเอาต์พุต',
  'bottompanel.terminal': 'เทอร์มินัล',
  'bottompanel.split': 'แบ่งหน้าจอ',
  'bottompanel.run': 'เรียกใช้ (F5)',
  'bottompanel.clear': 'ล้างข้อมูล',
  'bottompanel.stop': 'หยุด',
  'bottompanel.copyAll': 'คัดลอกทั้งหมด',
};

const hi = {
  'workspace.noFolderOpened': 'कोई फ़ोल्डर नहीं खोला गया',
  'workspace.openFolder': 'फ़ोल्डर खोलें',
  'quickopen.placeholder': 'नाम से फ़ाइलें खोजें (:लाइन लिखकर नेविगेट करें)...',
  'quickopen.noFilesFound': 'कोई मेल खाती फ़ाइल नहीं मिली',

  'titlebar.hideSidebar': 'साइडबार छुपाएं (Ctrl+B)',
  'titlebar.showSidebar': 'साइडबार दिखाएं (Ctrl+B)',
  'titlebar.newFile': 'नई फ़ाइल (Ctrl+N)',
  'titlebar.openFile': 'फ़ाइल खोलें (Ctrl+O)',
  'titlebar.saveFile': 'फ़ाइल सहेजें (Ctrl+S)',
  'titlebar.wordWrap': 'शब्द लपेटें (Word Wrap)',
  'titlebar.minimap': 'मिनीमैप',
  'titlebar.commandPalette': 'कमांड पैलेट (Ctrl+Shift+P)',
  'titlebar.settings': 'सेटिंग्स खोलें (Ctrl+,)',
  'titlebar.run': 'कोड चलाएँ (F5)',
  'titlebar.console': 'आउटपुट कंसोल',
  'titlebar.terminal': 'टर्मिनल (Ctrl+`)',
  'titlebar.minimize': 'छोटा करें',
  'titlebar.maximize': 'बड़ा करें',
  'titlebar.restore': 'पुनर्स्थापित करें',
  'titlebar.close': 'बंद करें',

  'tabbar.newTab': 'नया टैब (Ctrl+N)',
  'tabbar.closeTab': 'टैब बंद करें (Ctrl+W)',
  'tabbar.unsaved': 'असुरक्षित परिवर्तन। बंद करने के लिए क्लिक करें।',
  'tabbar.settings': 'सेटिंग्स',

  'tabmenu.close': 'बंद करें',
  'tabmenu.closeOthers': 'अन्य बंद करें',
  'tabmenu.closeRight': 'दाएं वाले बंद करें',
  'tabmenu.closeLeft': 'बाएं वाले बंद करें',
  'tabmenu.closeSaved': 'सहेजे गए बंद करें',
  'tabmenu.closeAll': 'सभी बंद करें',
  'tabmenu.reopenClosed': 'बंद टैब फिर से खोलें',
  'tabmenu.rename': 'नाम बदलें...',
  'tabmenu.duplicate': 'टैब डुप्लिकेट करें',
  'tabmenu.copyPath': 'पथ कॉपी करें',
  'tabmenu.copyName': 'फ़ाइल नाम कॉपी करें',
  'tabmenu.revealInExplorer': 'फ़ाइल एक्सप्लोरर में दिखाएं',
  'tabmenu.save': 'सहेजें',

  'sidebar.openEditors': 'खुले संपादक',
  'sidebar.newFile': 'नई फ़ाइल',
  'sidebar.openFile': 'फ़ाइल खोलें',
  'sidebar.filesCount': 'फ़ाइलें खुली हैं',
  'sidebar.settings': 'सेटिंग्स (Ctrl+,)',

  'statusbar.line': 'पंक्ति',
  'statusbar.col': 'कॉलम',
  'statusbar.selected': 'चयनित',
  'statusbar.spaces': 'स्पेस',
  'statusbar.encoding': 'फ़ाइल एन्कोडिंग',
  'statusbar.eol': 'पंक्ति का अंत',
  'statusbar.selectLanguage': 'भाषा मोड चुनें',
  'statusbar.notifications': 'सूचनाएं',
  'statusbar.errors': 'त्रुटियां',
  'statusbar.warnings': 'चेतावनियां',
  'statusbar.searchLanguage': 'भाषा मोड चुनें (उदा. ts, python, cpp, json)...',
  'statusbar.noLanguages': 'कोई मेल खाता भाषा मोड नहीं मिला',

  'palette.placeholder': 'कोई कमांड लिखें या खोजें...',
  'palette.escToClose': 'बंद करने के लिए Esc',
  'palette.noCommands': 'कोई कमांड नहीं मिली',
  'palette.cat.file': 'फ़ाइल',
  'palette.cat.edit': 'संपादित करें',
  'palette.cat.find': 'खोजें',
  'palette.cat.view': 'देखें',
  'palette.cat.preferences': 'प्राथमिकताएं',
  'palette.cat.themes': 'थीम्स',
  'palette.cat.language': 'भाषा',
  'palette.cmd.newFile': 'नई फ़ाइल',
  'palette.cmd.openFile': 'फ़ाइल खोलें...',
  'palette.cmd.saveFile': 'वर्तमान फ़ाइल सहेजें',
  'palette.cmd.saveAs': 'इस रूप में सहेजें...',
  'palette.cmd.find': 'दस्तावेज़ में खोजें',
  'palette.cmd.replace': 'खोजें और बदलें',
  'palette.cmd.toggleComment': 'पंक्ति टिप्पणी टॉगल करें',
  'palette.cmd.selectNext': 'अगला मिलान चुनें',
  'palette.cmd.gotoLine': 'पंक्ति पर जाएँ...',
  'palette.cmd.selectAll': 'सभी चुनें',
  'palette.cmd.undo': 'पूर्ववत करें (Undo)',
  'palette.cmd.redo': 'फिर से करें (Redo)',
  'palette.cmd.nextTab': 'अगला टैब',
  'palette.cmd.prevTab': 'पिछला टैब',
  'palette.cmd.closeTab': 'वर्तमान टैब बंद करें',
  'palette.cmd.toggleSidebar': 'साइडबार टॉगल करें',
  'palette.cmd.toggleWordWrap': 'वर्ड रैप टॉगल करें',
  'palette.cmd.toggleMinimap': 'मिनीमैप टॉगल करें',
  'palette.cmd.openSettings': 'सेटिंग्स खोलें (UI)',
  'palette.cmd.colorTheme': 'रंग थीम',
  'palette.cmd.changeLanguage': 'भाषा मोड बदलें',
  'palette.cmd.changeDisplayLanguage': 'प्रदर्शन भाषा बदलें',

  'settings.title': 'सेटिंग्स',
  'settings.preferences': '/ प्राथमिकताएं',
  'settings.backToEditor': 'संपादक पर वापस जाएं',
  'settings.resetAll': 'सभी रीसेट करें',
  'settings.searchPlaceholder': 'सेटिंग्स खोजें (थीम, फ़ॉन्ट, भाषा, टैब आकार)...',
  'settings.categories': 'श्रेणियां',
  'settings.cat.commonlyUsed': 'सामान्यतः प्रयुक्त',
  'settings.cat.appearance': 'रूप-रंग और थीम्स',
  'settings.cat.editor': 'टेक्स्ट संपादक',
  'settings.cat.files': 'फ़ाइलें और सत्र',
  'settings.cat.language': 'प्रदर्शन भाषा',

  'settings.preview.title': 'संपादक लाइव पूर्वावलोकन',
  'settings.preview.realtime': '(रीयल-टाइम में अपडेट होता है)',
  'settings.preview.theme': 'थीम',
  'settings.preview.font': 'फ़ॉन्ट',
  'settings.preview.tab': 'टैब',

  'settings.displayLanguage.title': 'एप्लिकेशन: प्रदर्शन भाषा',
  'settings.displayLanguage.desc': 'HyperEdit की यूज़र इंटरफ़ेस भाषा कॉन्फ़िगर करें।',
  'settings.theme.title': 'कार्यक्षेत्र: रंग थीम',
  'settings.theme.desc': 'एप्लिकेशन विंडो और कोड संपादक में प्रयुक्त रंग थीम निर्दिष्ट करें।',
  'settings.fontFamily.title': 'संपादक: फ़ॉन्ट परिवार',
  'settings.fontFamily.desc': 'संपादक पंक्तियों को प्रस्तुत करने के लिए फ़ॉन्ट परिवार।',
  'settings.fontSize.title': 'संपादक: फ़ॉन्ट आकार',
  'settings.fontSize.desc': 'पिक्सेल में फ़ॉन्ट आकार नियंत्रित करता है।',
  'settings.lineHeight.title': 'संपादक: पंक्ति ऊंचाई',
  'settings.lineHeight.desc': 'संपादक सामग्री का पंक्ति ऊंचाई गुणक।',
  'settings.tabSize.title': 'संपादक: टैब आकार',
  'settings.tabSize.desc': 'एक टैब के बराबर रिक्त स्थानों (spaces) की संख्या।',
  'settings.tabSize.spaces': 'रिक्त स्थान',
  'settings.wordWrap.title': 'संपादक: वर्ड रैप',
  'settings.wordWrap.desc': 'संपादक में लंबी पंक्तियों को लपेटने का तरीका नियंत्रित करता है।',
  'settings.minimap.title': 'संपादक > मिनीमैप: सक्षम',
  'settings.minimap.desc': 'नियंत्रित करता है कि दाईं ओर कोड मिनीमैप दिखाया जाए या नहीं।',
  'settings.cursorBlinking.title': 'संपादक: कर्सर ब्लिंकिंग एनीमेशन',
  'settings.cursorBlinking.desc': 'टेक्स्ट कर्सर की एनीमेशन शैली नियंत्रित करें।',
  'settings.cursorBlinking.smooth': 'सहज श्वास (VS Code शैली)',
  'settings.cursorBlinking.blink': 'क्लासिक ब्लिंक',
  'settings.cursorBlinking.solid': 'स्थिर (कोई ब्लिंक नहीं)',
  'settings.lineNumbers.title': 'संपादक: पंक्ति संख्याएँ',
  'settings.lineNumbers.desc': 'गटर में पंक्ति संख्याओं का प्रदर्शन नियंत्रित करें।',
  'settings.lineNumbers.on': 'चालू',
  'settings.lineNumbers.off': 'बंद',
  'settings.bracketMatching.title': 'संपादक: कोष्ठक मिलान',
  'settings.bracketMatching.desc': 'कर्सर पास होने पर मेल खाने वाले कोष्ठक को हाइलाइट करें।',
  'settings.autoCloseBrackets.title': 'संपादक: स्वतः बंद होने वाले कोष्ठक',
  'settings.autoCloseBrackets.desc': 'कोष्ठक और उद्धरण चिह्नों को स्वतः बंद करें।',
  'settings.activeLine.title': 'संपादक: सक्रिय पंक्ति हाइलाइट',
  'settings.activeLine.desc': 'वर्तमान सक्रिय पंक्ति को हाइलाइट करने का तरीका नियंत्रित करता है।',
  'settings.codeFolding.title': 'संपादक: कोड फोल्डिंग',
  'settings.codeFolding.desc': 'गटर में कोड फोल्डिंग सक्षम करें।',
  'settings.colorDecorators.title': 'संपादक: रंग सज्जाकार (Color Decorators)',
  'settings.colorDecorators.desc': 'हेक्स/आरजीबी रंगों के लिए इनलाइन रंग नमूना और पिकर दिखाएं।',
  'settings.renderWhitespace.title': 'संपादक: रिक्त स्थान प्रदर्शित करें',
  'settings.renderWhitespace.desc': 'अदृश्य रिक्त स्थान वर्णों को कैसे प्रदर्शित किया जाए।',
  'settings.renderWhitespace.none': 'कोई नहीं (अदृश्य)',
  'settings.renderWhitespace.all': 'सभी (बिंदु और प्रतीक दिखाएं)',
  'settings.sessionRestore.title': 'फ़ाइलें: सत्र पुनर्स्थापना (Notepad++ शैली)',
  'settings.sessionRestore.desc': 'पुनरारंभ करने पर खुले टैब और ड्राफ्ट स्वतः पुनर्स्थापित करें।',
  'settings.trimWhitespace.title': 'फ़ाइलें: पंक्ति के अंत का रिक्त स्थान हटाएं',
  'settings.trimWhitespace.desc': 'सहेजते समय पंक्ति के अंत में अतिरिक्त रिक्त स्थान हटाता है।',
  'settings.eol.title': 'फ़ाइलें: डिफ़ॉल्ट पंक्ति समाप्ति अनुक्रम',
  'settings.eol.desc': 'दस्तावेज़ की डिफ़ॉल्ट नई पंक्ति वर्ण (Unix के लिए LF, Windows के लिए CRLF)।',
  'settings.hotkeysHint': 'शॉर्टकट कुंजी:',
  'settings.autoSaved': 'डिस्क पर सहेजा गया',
  'settings.saveNotice': 'सभी सेटिंग्स स्वतः सहेजी जाती हैं और रीस्टार्ट के बाद भी बनी रहती हैं।',

  'empty.noDocumentOpen': 'कोई दस्तावेज़ या प्रोजेक्ट खुला नहीं है। आरंभ करने के लिए नीचे एक क्रिया चुनें:',
  'empty.project': 'प्रोजेक्ट:',
  'empty.newFile': 'नई फ़ाइल',
  'empty.openFile': 'फ़ाइल खोलें...',
  'empty.openFolder': 'फ़ोल्डर / प्रोजेक्ट खोलें...',
  'empty.quickOpen': 'फ़ाइल शीघ्र खोलें',
  'empty.commandPalette': 'कमांड पैलेट',
  'empty.openSettings': 'HyperEdit सेटिंग्स',

  'bottompanel.console': 'आउटपुट कंसोल',
  'bottompanel.terminal': 'टर्मिनल',
  'bottompanel.split': 'विभाजित करें',
  'bottompanel.run': 'चलाएँ (F5)',
  'bottompanel.clear': 'साफ़ करें',
  'bottompanel.stop': 'रोकें',
  'bottompanel.copyAll': 'सभी कॉपी करें',
};

const id = {
  'workspace.noFolderOpened': 'Tidak ada folder yang dibuka',
  'workspace.openFolder': 'Buka Folder',
  'quickopen.placeholder': 'Cari berkas berdasarkan nama (ketik :baris untuk navigasi)...',
  'quickopen.noFilesFound': 'Tidak ada berkas yang cocok ditemukan',

  'titlebar.hideSidebar': 'Sembunyikan Bilah Sisi (Ctrl+B)',
  'titlebar.showSidebar': 'Tampilkan Bilah Sisi (Ctrl+B)',
  'titlebar.newFile': 'Berkas Baru (Ctrl+N)',
  'titlebar.openFile': 'Buka Berkas (Ctrl+O)',
  'titlebar.saveFile': 'Simpan Berkas (Ctrl+S)',
  'titlebar.wordWrap': 'Bungkus Baris (Word Wrap)',
  'titlebar.minimap': 'Peta Mini',
  'titlebar.commandPalette': 'Palet Perintah (Ctrl+Shift+P)',
  'titlebar.settings': 'Buka Pengaturan (Ctrl+,)',
  'titlebar.run': 'Jalankan Kode (F5)',
  'titlebar.console': 'Konsol Output',
  'titlebar.terminal': 'Terminal (Ctrl+`)',
  'titlebar.minimize': 'Minimalkan',
  'titlebar.maximize': 'Maksimalkan',
  'titlebar.restore': 'Pulihkan',
  'titlebar.close': 'Tutup',

  'tabbar.newTab': 'Tab Baru (Ctrl+N)',
  'tabbar.closeTab': 'Tutup tab (Ctrl+W)',
  'tabbar.unsaved': 'Perubahan belum disimpan. Klik untuk menutup.',
  'tabbar.settings': 'Pengaturan',

  'tabmenu.close': 'Tutup',
  'tabmenu.closeOthers': 'Tutup Lainnya',
  'tabmenu.closeRight': 'Tutup ke Kanan',
  'tabmenu.closeLeft': 'Tutup ke Kiri',
  'tabmenu.closeSaved': 'Tutup yang Tersimpan',
  'tabmenu.closeAll': 'Tutup Semua Tab',
  'tabmenu.reopenClosed': 'Buka Kembali Tab yang Ditutup',
  'tabmenu.rename': 'Ganti Nama...',
  'tabmenu.duplicate': 'Duplikatkan Tab',
  'tabmenu.copyPath': 'Salin Jalur',
  'tabmenu.copyName': 'Salin Nama Berkas',
  'tabmenu.revealInExplorer': 'Tampilkan di File Explorer',
  'tabmenu.save': 'Simpan',

  'sidebar.openEditors': 'Editor Terbuka',
  'sidebar.newFile': 'Berkas Baru',
  'sidebar.openFile': 'Buka Berkas',
  'sidebar.filesCount': 'berkas terbuka',
  'sidebar.settings': 'Pengaturan (Ctrl+,)',

  'statusbar.line': 'Brs',
  'statusbar.col': 'Kol',
  'statusbar.selected': 'terpilih',
  'statusbar.spaces': 'Spasi',
  'statusbar.encoding': 'Pengkodean Berkas',
  'statusbar.eol': 'Akhir Baris',
  'statusbar.selectLanguage': 'Pilih Mode Bahasa',
  'statusbar.notifications': 'Pemberitahuan',
  'statusbar.errors': 'Kesalahan',
  'statusbar.warnings': 'Peringatan',
  'statusbar.searchLanguage': 'Pilih Mode Bahasa (cth. ts, python, cpp, json)...',
  'statusbar.noLanguages': 'Tidak ada mode bahasa yang cocok',

  'palette.placeholder': 'Ketik perintah atau cari...',
  'palette.escToClose': 'untuk menutup',
  'palette.noCommands': 'Tidak ada perintah yang cocok ditemukan',
  'palette.cat.file': 'Berkas',
  'palette.cat.edit': 'Edit',
  'palette.cat.find': 'Cari',
  'palette.cat.view': 'Tampilan',
  'palette.cat.preferences': 'Preferensi',
  'palette.cat.themes': 'Tema',
  'palette.cat.language': 'Bahasa',
  'palette.cmd.newFile': 'Berkas Baru',
  'palette.cmd.openFile': 'Buka Berkas...',
  'palette.cmd.saveFile': 'Simpan Berkas Saat Ini',
  'palette.cmd.saveAs': 'Simpan Sebagai...',
  'palette.cmd.find': 'Cari di Dokumen',
  'palette.cmd.replace': 'Cari dan Ganti',
  'palette.cmd.toggleComment': 'Alihkan Komentar Baris',
  'palette.cmd.selectNext': 'Pilih Kemunculan Berikutnya',
  'palette.cmd.gotoLine': 'Buka Baris...',
  'palette.cmd.selectAll': 'Pilih Semua',
  'palette.cmd.undo': 'Urungkan (Undo)',
  'palette.cmd.redo': 'Ulangi (Redo)',
  'palette.cmd.nextTab': 'Tab Berikutnya',
  'palette.cmd.prevTab': 'Tab Sebelumnya',
  'palette.cmd.closeTab': 'Tutup Tab Saat Ini',
  'palette.cmd.toggleSidebar': 'Alihkan Bilah Sisi',
  'palette.cmd.toggleWordWrap': 'Alihkan Bungkus Baris',
  'palette.cmd.toggleMinimap': 'Alihkan Peta Mini',
  'palette.cmd.openSettings': 'Buka Pengaturan (UI)',
  'palette.cmd.colorTheme': 'Tema Warna',
  'palette.cmd.changeLanguage': 'Ubah Mode Bahasa',
  'palette.cmd.changeDisplayLanguage': 'Ubah Bahasa Tampilan',

  'settings.title': 'Pengaturan',
  'settings.preferences': '/ Preferensi',
  'settings.backToEditor': 'Kembali ke Editor',
  'settings.resetAll': 'Atur Ulang Semua',
  'settings.searchPlaceholder': 'Cari pengaturan (tema, font, bahasa, ukuran tab)...',
  'settings.categories': 'Kategori',
  'settings.cat.commonlyUsed': 'Sering Digunakan',
  'settings.cat.appearance': 'Tampilan & Tema',
  'settings.cat.editor': 'Editor Teks',
  'settings.cat.files': 'Berkas & Sesi',
  'settings.cat.language': 'Bahasa Tampilan',

  'settings.preview.title': 'Pratinjau Langsung Editor',
  'settings.preview.realtime': '(Diperbarui secara waktu nyata)',
  'settings.preview.theme': 'Tema',
  'settings.preview.font': 'Font',
  'settings.preview.tab': 'Tab',

  'settings.displayLanguage.title': 'Aplikasi: Bahasa Tampilan',
  'settings.displayLanguage.desc': 'Konfigurasikan bahasa antarmuka pengguna HyperEdit.',
  'settings.theme.title': 'Ruang Kerja: Tema Warna',
  'settings.theme.desc': 'Menentukan tema warna yang digunakan pada jendela aplikasi dan editor kode.',
  'settings.fontFamily.title': 'Editor: Keluarga Font',
  'settings.fontFamily.desc': 'Mengontrol jenis font yang digunakan untuk menampilkan baris kode.',
  'settings.fontSize.title': 'Editor: Ukuran Font',
  'settings.fontSize.desc': 'Mengontrol ukuran font dalam piksel.',
  'settings.lineHeight.title': 'Editor: Tinggi Baris',
  'settings.lineHeight.desc': 'Pengali tinggi baris pada konten editor.',
  'settings.tabSize.title': 'Editor: Ukuran Tab',
  'settings.tabSize.desc': 'Jumlah spasi yang setara dengan satu tab.',
  'settings.tabSize.spaces': 'Spasi',
  'settings.wordWrap.title': 'Editor: Bungkus Baris',
  'settings.wordWrap.desc': 'Mengontrol bagaimana baris panjang dibungkus dalam editor.',
  'settings.minimap.title': 'Editor > Peta Mini: Diaktifkan',
  'settings.minimap.desc': 'Mengontrol apakah peta mini interaktif ditampilkan di sisi kanan.',
  'settings.cursorBlinking.title': 'Editor: Animasi Kedipan Kursor',
  'settings.cursorBlinking.desc': 'Mengontrol gaya animasi kedipan kursor teks.',
  'settings.cursorBlinking.smooth': 'Bernapas Halus (Gaya VS Code)',
  'settings.cursorBlinking.blink': 'Kedipan Klasik',
  'settings.cursorBlinking.solid': 'Padat Tanpa Kedip',
  'settings.lineNumbers.title': 'Editor: Nomor Baris',
  'settings.lineNumbers.desc': 'Mengontrol tampilan nomor baris di gutter.',
  'settings.lineNumbers.on': 'Nyala',
  'settings.lineNumbers.off': 'Mati',
  'settings.bracketMatching.title': 'Editor: Pencocokan Kurung',
  'settings.bracketMatching.desc': 'Sorot kurung yang cocok saat kursor berada di dekatnya.',
  'settings.autoCloseBrackets.title': 'Editor: Penutupan Kurung Otomatis',
  'settings.autoCloseBrackets.desc': 'Secara otomatis memasukkan kurung dan tanda kutip penutup.',
  'settings.activeLine.title': 'Editor: Sorot Baris Aktif',
  'settings.activeLine.desc': 'Mengontrol cara editor menyorot baris aktif saat ini.',
  'settings.codeFolding.title': 'Editor: Pelipatan Kode',
  'settings.codeFolding.desc': 'Mengaktifkan pelipatan blok fungsi dan kode di gutter.',
  'settings.colorDecorators.title': 'Editor: Dekorator Warna',
  'settings.colorDecorators.desc': 'Menampilkan kotak warna inline dan pemilih warna untuk hex/rgb/hsl.',
  'settings.renderWhitespace.title': 'Editor: Render Spasi Kosong',
  'settings.renderWhitespace.desc': 'Mengontrol cara editor merender karakter spasi dan tab yang tidak terlihat.',
  'settings.renderWhitespace.none': 'Tidak Ada (Tersembunyi)',
  'settings.renderWhitespace.all': 'Semua (Tampilkan titik)',
  'settings.sessionRestore.title': 'Berkas: Pemulihan Sesi (Gaya Notepad++)',
  'settings.sessionRestore.desc': 'Secara otomatis memulihkan tab yang terbuka dan draf saat membuka kembali.',
  'settings.trimWhitespace.title': 'Berkas: Pangkas Spasi di Akhir Baris',
  'settings.trimWhitespace.desc': 'Menghapus spasi tambahan di akhir baris saat menyimpan.',
  'settings.eol.title': 'Berkas: Urutan Akhir Baris Default',
  'settings.eol.desc': 'Karakter baris baru default (LF untuk Unix/macOS, CRLF untuk Windows).',
  'settings.hotkeysHint': 'Tombol Pintas:',
  'settings.autoSaved': 'Tersimpan ke disk',
  'settings.saveNotice': 'Semua pengaturan disimpan otomatis ke disk dan tetap ada saat aplikasi dimulai ulang.',

  'empty.noDocumentOpen': 'Tidak ada dokumen atau proyek yang terbuka. Pilih tindakan di bawah untuk memulai:',
  'empty.project': 'Proyek:',
  'empty.newFile': 'Berkas Baru',
  'empty.openFile': 'Buka Berkas...',
  'empty.openFolder': 'Buka Folder / Proyek...',
  'empty.quickOpen': 'Navigasi Berkas Cepat',
  'empty.commandPalette': 'Palet Perintah',
  'empty.openSettings': 'Pengaturan HyperEdit',

  'bottompanel.console': 'Konsol Output',
  'bottompanel.terminal': 'Terminal',
  'bottompanel.split': 'Bagi Layar',
  'bottompanel.run': 'Jalankan (F5)',
  'bottompanel.clear': 'Bersihkan',
  'bottompanel.stop': 'Hentikan',
  'bottompanel.copyAll': 'Salin Semua',
};

function formatDict(name, dict) {
  let s = `export const ${name}: TranslationDictionary = {\n`;
  for (const [k, v] of Object.entries(dict)) {
    const escaped = v.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
    s += `  '${k}': '${escaped}',\n`;
  }
  s += `};\n\n`;
  return s;
}

let out = `import { TranslationDictionary } from '../../types/i18n';\n\n`;
out += `// 简体中文 (Chinese Simplified)\n` + formatDict('zhCnTranslations', zhCn);
out += `// 繁體中文 (Chinese Traditional)\n` + formatDict('zhTwTranslations', zhTw);
out += `// 日本語 (Japanese)\n` + formatDict('jaTranslations', ja);
out += `// 한국어 (Korean)\n` + formatDict('koTranslations', ko);
out += `// Tiếng Việt (Vietnamese)\n` + formatDict('viTranslations', vi);
out += `// ภาษาไทย (Thai)\n` + formatDict('thTranslations', th);
out += `// हिन्दी (Hindi)\n` + formatDict('hiTranslations', hi);
out += `// Bahasa Indonesia (Indonesian)\n` + formatDict('idTranslations', id);

fs.writeFileSync('src/i18n/locales/asian.ts', out, 'utf8');
console.log('Successfully written src/i18n/locales/asian.ts');
